### ISSUE TITLE
Voice connection timeout

### ISSUE THREAD

**Issue by bjxke** [briantanner/eris-lavalink#4] opened 2017-09-23 08:48 UTC
```js
Error: Voice connection timeout
     at Timeout.pendingGuilds.(anonymous function).timeout.setTimeout [as _onTimeout] (/home/jake/discord/Adonis/node_modules/eris-lavalink/src/PlayerManager.js:323:25)
     at ontimeout (timers.js:469:11)
     at tryOnTimeout (timers.js:304:5)
     at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by briantanner** [comment] 2017-09-27 21:03
Could you provide any more info on it?

**Comment by bjxke** [comment] 2017-09-28 16:37
Not much info to be provided. Happens quite often and I know other large bots that have this problem such as Pancake. Really not sure what causes it.

**Comment by minemidnight** [comment] 2017-09-28 22:53
I get this error a bunch too. Used to happen with Eris, might want to ask abal on how he fixed it.

**Comment by minemidnight** [comment] 2017-10-07 17:10
Any updates on this? It’s pretty bad for my users.

**Comment by briantanner** [comment] 2017-10-07 17:12
Have any logs or debug that might help pinpoint the cause?

**Comment by minemidnight** [comment] 2017-10-07 17:39
Nope. All I know is Eris used to have the same issue.

**Comment by itslukej** [comment] 2017-10-08 09:45
Getting this too, however I've noticed that it happens more after the shard has lost connection with one of the voice nodes. https://sentry.davinci.sh/share/issue/332e333535/ 
![image](https://user-images.githubusercontent.com/8759737/31315719-07d973aa-ac16-11e7-91d0-abf829efe733.png)

**Comment by bjxke** [comment] 2017-10-21 08:13
It's happening a lot more now than it ever has to me. Got to the point where it won't play.

**Comment by briantanner** [comment] 2017-10-21 08:15
Any help would be appreciated. I haven't found anything in the client that could be causing it.

It is fixable by restarting the affected Lavalink node, it seems to get in a connect loop which is what I find causes it often times.

**Comment by bjxke** [comment] 2017-10-21 08:27
Alright, its just constant. 
![image](https://user-images.githubusercontent.com/20141653/31849900-14aebf96-b642-11e7-9a64-95fbf231628a.png)

**Comment by briantanner** [comment] 2017-10-21 08:30
Yeah, that doesn't help much.. The best that I've been able to figure out so far is that there's either something not implemented correctly in the client, or have been told it could be a JDA-Audio issue. However, I've looked through the client up and down for weeks looking for the cause and can't see anything glaring.

**Comment by DoctorDarkMagic** [comment] 2017-10-22 17:08
I've just updated to the latest version on GitHub and it has removed my issue (thanks @Thewsomeguy ). I'm not sure that this issue won't appear again because I received the error even before Eris 0.8.0.

**Comment by briantanner** [comment] 2017-10-22 17:12
@DoctorDarkMagic the latest version of eris?

**Comment by DoctorDarkMagic** [comment] 2017-10-22 17:32
Eris 0.8.0

**Comment by itslukej** [comment] 2017-11-12 00:09
I too have looked through eris-lavalink and I've seen nothing that could lead to this issue, given that JDA-Audio is experimental, It's probably coming from the lavalink server itself. I could ask someone using the JDA lavalink client to see if they have also experienced it

**Comment by p4rkrs** [comment] 2017-11-17 16:44
I have a lot of that too. The people need to kick the bot, and wait like 5 minutes & thats will work

**Comment by itslukej** [comment] 2017-12-05 20:26
We are now having cases where the bot will give a `Voice connection timeout` when it shows as not in the voice channel (compared to the previous times where the bot would show as in the voice channel), the only solution we have found so far to this is restarting the whole eris client (which is 5 shards, ~4.5k guilds for us, quite annoying 😕)

**Comment by Vappe** [comment] 2017-12-05 20:31
@itslukej @briantanner @DoctorDarkMagic @minemidnight @itskiru

**Comment by itslukej** [comment] 2017-12-10 17:58
Very sure this issue is on the lavalink server side. A 'fix' we have found for our users is to have them connect to a different lavalink server than the one that they are getting vc timeouts on
![image](https://user-images.githubusercontent.com/8759737/33807775-ada244b2-ddd3-11e7-9ab6-2972754e8866.png)

**Comment by freyacodes** [comment] 2017-12-15 16:31
Grepping the affected guild's id in the affected LL server's debug.log might give some clues

**Comment by bjxke** [comment] 2017-12-17 15:52
I no longer get this issue but people still say they get it with other bots so I'll keep this issue open.

**Comment by p4rkrs** [comment] 2017-12-18 02:20
@DoctorDarkMagic How?

**Comment by itslukej** [comment] 2017-12-18 08:14
@itskiru #11

**Comment by briantanner** [comment] 2018-02-11 15:24
Closing due to age, deprecation, and new bug fixes in the v1 branch

**Closed as completed by briantanner** 2018-02-11 15:24 UTC

**Comment by Bacon1661** [comment] 2018-02-14 21:29
Still getting this issue.

**Comment by itslukej** [comment] 2018-02-14 21:30
@Bacon1153 Have you updated eris-lavalink and lavalink server to v2?

**Comment by Bacon1661** [comment] 2018-02-15 00:54
@itslukej Yes, I've gotten this both on v1 and v2.

**Comment by briantanner** [comment] 2018-02-15 00:58
This happens afaik, have always had this issue when dealing with music, if you can get more info on what's causing it and/or identify a bug in eris-lavalink, feel free to open a new issue.

Some possible causes:
**Permissions** - View Channel, Connect, Use Voice Activity
**Voice Server/Region** - Not sure how common, but happens on occasion that the voice server is to blame, changing region gets you on a new server.

**Comment by Bacon1661** [comment] 2018-02-15 01:09
It's strange, because some people don't have this issue at all and some people (like me) always get the error. I'll look into it.

**Comment by Bacon1661** [comment] 2018-02-15 15:19
I've been talking to some people and someone said that voiceServerUpdate is never getting called, causing the timeout to never be resolved. Very interesting.

**Comment by briantanner** [comment] 2018-02-15 15:22
That would be because your bot never joins the channel, therefore never gets a voice server update, and times out... I would check the things I mentioned above, namely that the permissions are correct when it happens.

**Comment by PassTheMayo** [comment] 2018-03-01 01:51
I've been getting the same issue, but it's seemed to go away after I messed with the code. It hasn't been happening today.

**Comment by briantanner** [comment] 2018-03-01 01:52
@PassTheMayo "after I messed with the code" would be nice to know what this means if it's a bug in eris-lavalink

**Comment by PassTheMayo** [comment] 2018-03-01 02:00
@briantanner I'm not sure what I did, because I changed a lot. I can't explain what I did, but it just doesn't do that now.

**Comment by p4rkrs** [comment] 2018-03-01 02:01
Just use 0.1.2 with V1 of lavalink and everything is okay.

**Comment by Bacon1661** [comment] 2018-03-01 02:25
Why would you use v1?

**Comment by briantanner** [comment] 2018-03-01 02:27
I would recommend people update to Lavalink v2 and eris-lavalink ^1.0.x

**Comment by briantanner** [comment] 2018-03-01 02:34
I'm locking this issue, if anyone can identify a bug in **eris-lavalink** with a way to reproduce, please submit a new issue. Otherwise, refer to my previous comments, and make an effort to correct the issue on your end first. If that doesn't work, please provide some debugging information or even submit a pull request if you think you can contribute anything.
